
name: Super-Linter

# Запускается при создании pull request в ветку dev
on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4

      # Запускаем Super-Linter для проверки JavaScript
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_ES: true # Включаем линтинг JavaScript с ESLint
          FILTER_REGEX_INCLUDE: (frontend/src|microservices/catalog-service/src) # Проверяем только папки с кодом
